name: Build and Deploy

on:
  push:
    branches: [main]
  
  workflow_dispatch:

jobs:
  build-and-deploy:
      name: deploy mi app flask
      runs-on: ubuntu-latest
      steps:
        - name: check out flask-app
          uses: actions/checkout@v3
        - name: Istall and Build
          run: python freezer.py
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4
          with:
            folder: build